<?php

namespace ContainerDg5BCWr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UMyBt7CService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UMyBt7C' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UMyBt7C'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['privates', '.errored.D.gB3_y', NULL, 'Cannot determine controller argument for "App\\Controller\\PrestationController::create()": the $manager argument is type-hinted with the non-existent class or interface: "App\\Controller\\ObjectManager". Did you forget to add a use statement?'],
        ], [
            'manager' => '?',
        ]);
    }
}
