<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8jZ9WdH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8jZ9WdH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8jZ9WdH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8jZ9WdH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8jZ9WdH\App_KernelDevDebugContainer([
    'container.build_hash' => '8jZ9WdH',
    'container.build_id' => '89d48bc2',
    'container.build_time' => 1633626382,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8jZ9WdH');
