<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW0iKEcu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW0iKEcu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW0iKEcu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW0iKEcu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW0iKEcu\App_KernelDevDebugContainer([
    'container.build_hash' => 'W0iKEcu',
    'container.build_id' => '3904fca2',
    'container.build_time' => 1633895013,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW0iKEcu');
