<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'home' => [[], ['_controller' => 'App\\Controller\\PresentationController::home'], [], [['text', '/']], [], []],
    'presentation' => [['id'], ['_controller' => 'App\\Controller\\PresentationController::presentation'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/presentation']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\PresentationController::login'], [], [['text', '/login']], [], []],
    'page_edit' => [['id'], ['_controller' => 'App\\Controller\\PresentationController::form'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/page']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
