<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'acceuil' => [[], ['_controller' => 'App\\Controller\\AcceuilController::index'], [], [['text', '/']], [], []],
    'prestation' => [[], ['_controller' => 'App\\Controller\\PrestationController::index'], [], [['text', '/prestation']], [], []],
    'prestation_create' => [[], ['_controller' => 'App\\Controller\\PrestationController::create'], [], [['text', '/prestation/new']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
